version: "0.2"
ignorePaths: [.gitignore, .trunk/trunk.yaml]
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
dictionaries:
  - en-gb
  - python
  - python-common
  - posix-errno
  - custom-dictionary
words: []
ignoreWords: []
import: []
